export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
export const GET_PRODUCTS_PENDING = 'GET_PRODUCTS_PENDING';

export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_PENDING = 'GET_CART_PENDING';
export const GET_CART_FAILD = 'GET_CART_FAILD';
export const CART = 'CART';
export const UPDATE_CARD = 'UPDATE_CARD';
export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const DELETE = 'DELETE';
// MyItem
export const MY_ITEM = 'MY_ITEM';
export const RESET_CARD = 'RESET_CARD';
export const INCREASE_MY_ITEM = 'INCREASE_MY_ITEM';
export const DECREASE_MY_ITEM = 'DECREASE_MY_ITEM';
export const DELETE_MY_ITEM = 'DELETE_MY_ITEM';
// Authentication
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_PENDING = 'LOGIN_PENDING';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// My Information
export const GET_ME = 'GET_ME';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILED = 'GET_ME_FAILED';
export const GET_ME_PENDING = 'GET_ME_PENDING';

// Get Category
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED';
export const GET_CATEGORY_PENDING = 'GET_CATEGORY_PENDING';

// Get Products Category
export const GET_CATEGORY_PRODUCTS = 'GET_CATEGORY_PRODUCTS';
export const GET_CATEGORY_PRODUCTS_SUCCESS = 'GET_CATEGORY_PRODUCTS_SUCCESS';
export const GET_CATEGORY_PRODUCTS_FAILED = 'GET_CATEGORY_PRODUCTS_FAILED';
export const GET_CATEGORY_PRODUCTS_PENDING = 'GET_CATEGORY_PRODUCTS_PENDING';

// Get Products Details
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILED = 'GET_PRODUCT_DETAIL_FAILED';
export const GET_PRODUCT_DETAIL_PENDING = 'GET_PRODUCT_DETAIL_PENDING';
